### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mupinnn** [mupinnn/dsa#1]
Add support for TypeScript in purpose I want to more often use it on my daily-basis activity.

## Todo
- [x] setup typescript
- [x] setup ts-node
- [x] setup ts-jest
- [x] make sure JavaScript can still be used
- [x] make sure jest load the config based on the language (js/ts)
